"""empty message

Revision ID: b903b8a1cd52
Revises: de803637360e
Create Date: 2023-03-08 22:46:38.199737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b903b8a1cd52'
down_revision = 'de803637360e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fieldsOfStudyAdded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flag')
    # ### end Alembic commands ###
