"""empty message

Revision ID: de803637360e
Revises: f08fd418c437
Create Date: 2023-03-08 21:07:23.219545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de803637360e'
down_revision = 'f08fd418c437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_of_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field')
    )
    op.drop_table('email_verification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('format', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('disposable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dns', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='email_verification_pkey'),
    sa.UniqueConstraint('domain', name='email_verification_domain_key'),
    sa.UniqueConstraint('email', name='email_verification_email_key')
    )
    op.drop_table('field_of_study')
    # ### end Alembic commands ###
