"""empty message

Revision ID: f08fd418c437
Revises: 3e037f2a631b
Create Date: 2023-03-07 19:51:48.036577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08fd418c437'
down_revision = '3e037f2a631b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('disposable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dns', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['domain'])
        batch_op.drop_column('can_connect_smtp')
        batch_op.drop_column('is_disposable')
        batch_op.drop_column('is_disabled')
        batch_op.drop_column('accepts_mail')
        batch_op.drop_column('is_deliverable')
        batch_op.drop_column('is_inbox_full')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_inbox_full', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_deliverable', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accepts_mail', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_disposable', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_connect_smtp', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dns')
        batch_op.drop_column('disposable')
        batch_op.drop_column('domain')
        batch_op.drop_column('format')

    # ### end Alembic commands ###
